name: crawl
on:
  push:
    branches: main
  schedule:
  - cron: '24 6/6 * * *'
  workflow_dispatch:
concurrency: crawl
jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
    - uses: zhangyoufu/actions/checkout@main
      timeout-minutes: 1

    - name: Crawl packages and synchronize to GitHub releases
      env:
        DEBUG_LOG: ${{ runner.debug }}
        GH_TOKEN: ${{ github.token }}
        REDHAT_API_OFFLINE_TOKEN: ${{ secrets.REDHAT_API_OFFLINE_TOKEN }}
        REDHAT_USER_ID: ${{ secrets.REDHAT_USER_ID }} # for CI log masking only
        TMPDIR: ${{ runner.temp }}
      run: ./crawl.sh
